chart/Chart.yaml

See: https://github.com/bitnami/charts/issues/10539
Resolves: https://github.com/openebs/mayastor-extensions/issues/1

fix(etcd): point to specific commit of the bitnami repo

---

chart/templates/mayastor/io/io-engine-daemonset.yaml

Signed-off-by: Abhinandan Purkait <abhinandan.purkait@mayadata.io>

chore: add nodename arg to io-engine ds

---

_config.yml

Signed-off-by: Abhinandan Purkait <abhinandan.purkait@mayadata.io>

chore: add new theme to github page

---

.pre-commit-config.yaml
shell.nix

fix: add missing cacert for pure environments

---

chart/templates/mayastor/csi/csi-controller-deployment.yaml

Signed-off-by: Abhinandan Purkait <abhinandan.purkait@mayadata.io>

chore: remove io-engine-selector arg from csi-controller

---

Cargo.lock
call-home/Cargo.toml
nix/pkgs/extensions/cargo-project.nix
operators/Cargo.toml
operators/common/src/helm/mod.rs
operators/common/src/lib.rs
operators/src/lib.rs
operators/src/upgrade/common/constants.rs
operators/src/upgrade/common/mod.rs
operators/src/upgrade/k8s/api_resources/deployment.rs
operators/src/upgrade/k8s/api_resources/mod.rs
operators/src/upgrade/k8s/api_resources/rbac.rs
operators/src/upgrade/k8s/crd/mod.rs
operators/src/upgrade/k8s/crd/v0.rs
operators/src/upgrade/k8s/mod.rs
operators/src/upgrade/main.rs
operators/src/upgrade/mod.rs
operators/upgrade/src/bin/main.rs
operators/upgrade/src/crd/mod.rs
shell.nix

Signed-off-by: rajaSahil <sahilraja242@gmail.com>
- Adds crd(UpgradeAction)
- Adds rbac
- Adds deployement, service for operator
- There can be changes in the code while implementing different parts. Mainly addition of functions.

feat(upgrade): add crd and k8s api resources

---

chart/templates/mayastor/ha/ha-node-daemonset.yaml
chart/values.yaml

HA Node agent is now deployed as a DaemonSet.

feat(ha-node): added helm chart for ha node agent

---

Cargo.lock
call-home/Cargo.toml
call-home/src/collector.rs
call-home/src/collector/k8s_client.rs
call-home/src/common.rs
call-home/src/common/constants.rs
call-home/src/common/errors.rs
call-home/src/main.rs
call-home/src/transmitter.rs
call-home/src/transmitter/client.rs
call-home/src/transmitter/encryption.rs

This is a work in progress PR for the Swarm transmitter.
This depends on #18 .

feat(call-home): add transmitter

---

nix/pkgs/extensions/default.nix
operators/Cargo.toml
operators/src/upgrade/common/error.rs
operators/src/upgrade/common/mod.rs
operators/src/upgrade/helm/client.rs
operators/src/upgrade/helm/mod.rs
operators/src/upgrade/mod.rs

Signed-off-by: rajaSahil <sahilraja242@gmail.com>
- Add helm client
- Runs helm commands in the container.

feat(upgrade): add helm client

---

.gitmodules

Pin dependency git submodule repos to the most recent commit in the release/2.0 branch.

fix(dependencies): pin git submodules to release/2.0 branches

---

Jenkinsfile
scripts/release.sh

fix: update release.sh with the control-plane repo

---

Jenkinsfile
scripts/release.sh

45: fix: update release.sh with the control-plane repo r=tiagolobocastro a=tiagolobocastro
Co-authored-by: Tiago Castro <tiagolobocastro@gmail.com>

chore: cherry-pick pull request #45 from develop

---

default.nix
nix/overlay.nix
nix/pkgs/images/default.nix

This also updates git submodules to the latest commit in openebs/mayastor-control-plane release/2.0 branch.

Cherry-pick #50 into release/2.0 branch

---

chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/templates/mayastor/agents/core/agent-core-service.yaml
chart/values.yaml

This reverts commit a846a8269cbfe040e3df631365914e2484da3bac, reversing changes made to 4494135c8b845e60383157efdec7937e9f1146da.

revert: pull request #47

---

Cargo.lock
operators/Cargo.toml
operators/src/lib.rs
operators/src/upgrade/bin/main.rs
operators/src/upgrade/common/error.rs
operators/src/upgrade/common/mod.rs
operators/src/upgrade/config.rs
operators/src/upgrade/helm/client.rs
operators/src/upgrade/helm/mod.rs
operators/src/upgrade/k8s/client.rs
operators/src/upgrade/k8s/mod.rs
operators/src/upgrade/main.rs
operators/src/upgrade/mod.rs
operators/src/upgrade/rest/mod.rs
operators/src/upgrade/rest/service.rs

Signed-off-by: rajaSahil <sahilraja242@gmail.com>
- Add rest
- Integrate components
Copy of #42 (bors issue)

feat(upgrade): add rest and integrate components

---

call-home/src/main.rs

At this point, if the call-home transmission module fails to reach the receiver API server, it retries 3 times and panics.
This PR changes this behavior, and after 3 retries, the error is logged and we don't panic.

fix(call-home): avoid panic when transmission fails

---

call-home/src/main.rs

Cherry-pick #55 into release/2.0 branch

---

chart/templates/mayastor/agents/ha/ha-node-daemonset.yaml
chart/templates/mayastor/csi/csi-node-daemonset.yaml
chart/values.yaml

Signed-off-by: Abhinandan Purkait <purkaitabhinandan@gmail.com>

chore: ha-node nvme connect over uds to csi-node

---

chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/templates/mayastor/apis/api-rest-deployment.yaml
chart/templates/mayastor/priority-class/priority-class.yaml
chart/values.yaml

- Adds the toleration that would cause early eviction of pods incase the node is down/unreachable.
- Adds a PriorityClass that would help in more prior scheduling of the component.
- Adds a key to edit rest pod replicas.
Signed-off-by: Abhinandan Purkait <purkaitabhinandan@gmail.com>

chore: add toleration and priority class for early eviction and scheduling

---

Cargo.lock
k8s/plugin/Cargo.toml
k8s/plugin/README.md
k8s/plugin/src/constant.rs
k8s/plugin/src/main.rs
k8s/plugin/src/resources/mod.rs
k8s/plugin/src/resources/objects.rs
k8s/plugin/src/resources/upgrade.rs
operators/src/upgrade/common/constants.rs

Introduce two new commands 
- kubectl mayastor install upgrade-operator
- kubectl mayastor uninstall upgrade-operator
Signed-off-by: sinhaashish <ashi.sinha.87@gmail.com>

feat(upgrade): add install uninstall command for upgrade-operator

---

k8s/supportability/src/collect/resource_dump.rs

Signed-off-by: Vandana Varakantham <vandana.varakantham@datacore.com>

feat(supportability): add success log to the etcd dump command

---

.github/workflows/release-binaries.yml

ci(gha): add cachix to binary build

---

chart/Chart.yaml
chart/values.yaml

Signed-off-by: Abhinandan Purkait <abhinandan.purkait@mayadata.io>

chore: bump up etcd chart version from 6.2.3 to 8.6.0

---

.pre-commit-config.yaml
Jenkinsfile
chart/README.md
chart/README.md.tmpl
chart/templates/_helpers.tpl
chart/templates/mayastor/csi/csi-node-daemonset.yaml
chart/templates/mayastor/io/io-engine-daemonset.yaml
chart/values.yaml
nix/pkgs/extensions/cargo-project.nix
nix/pkgs/utils/default.nix
scripts/helm/generate-readme.sh
scripts/helm/publish-chart-yaml.sh
scripts/helm/shell.nix

ci: add helm-docs Jenkins test
---
chore: update values.yaml and update README
Add comments notation and tidy up some values.
---
feat(helm-docs): autogenerate helm docs
Add helm-docs to nix-shell.
Add template for generating the README.
Add script that generates the README.
---
chore(shell): add commitlinter as git pre-commit hook
Add the commitlinter as a pre-commit hook
---
chore: update control-plane dep
---
fix: update image pull policy on tag

feat(helm-docs): autogenerate helm docs

---

chart/README.md
chart/README.md.tmpl

fix: registry link to this repo

---

.github/workflows/develop-to-release-chart.yml
scripts/helm/generate-readme.sh
shell.nix

fix(gha/bot): update README when creating develop=>release PR

---

chart/README.md
chart/templates/mayastor/apis/api-rest-service.yaml
chart/values.yaml

Signed-off-by: Abhinandan Purkait <purkaitabhinandan@gmail.com>

chore: make rest api node port service configurable

---

chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/templates/mayastor/agents/core/agent-core-service.yaml
chart/templates/mayastor/agents/ha/ha-node-daemonset.yaml
chart/templates/mayastor/apis/api-rest-deployment.yaml
chart/templates/mayastor/apis/api-rest-service.yaml
chart/templates/mayastor/csi/csi-controller-deployment.yaml
chart/templates/mayastor/csi/csi-node-daemonset.yaml
chart/templates/mayastor/io/io-engine-daemonset.yaml
chart/templates/mayastor/metrics/metrics-exporter-pool-service.yaml
chart/templates/mayastor/obs/obs-callhome-deployment.yaml
chart/templates/mayastor/operators/operator-diskpool-deployment.yaml

Cherry-pick #106 to develop branch.

Cherry-pick #106 to develop branch

---

chart/README.md
chart/values.yaml

Changes:
- Raise memory limit for agent-core container to 128MiB
- Raise memory request for agent-core container to 32MiB
- Raise memory limit for HA cluster agent to 64MiB

Cherry-pick #109 to develop branch

---

Cargo.lock
Cargo.toml
console-logger/Cargo.toml
console-logger/src/console.rs
k8s/plugin/Cargo.toml
k8s/plugin/src/main.rs
k8s/plugin/src/resources/mod.rs
k8s/plugin/src/resources/upgrade.rs
k8s/plugin/src/user_prompt.rs
nix/pkgs/extensions/cargo-project.nix

Add a note for the hot upgrade : `Note : During upgrade if you create single replica volumes then you may loose them`
Add `upgrade_operator_endpoint` to upgrade and upgrade status command  only.

add promt for single replica volume

---

chart/templates/mayastor/rbac/rbac.yaml

Need this to update crd from diskpool operator

chore: adding access on get and update verbs of crd

---

k8s/supportability/src/collect/logs/mod.rs

dump command now collects both historical and current logs.
```
kubectl mayastor dump system
```
```
➜  logs  tree
.
|-- agent-core
|   |-- loki-agent-core.log
|   |-- loki-agent-ha-cluster.log
|   `-- mayastor-node2_mayastor-agent-core-5f6b6dd979-tf6wb ---> kubectl logs
|       |-- agent-core.log
|       `-- agent-ha-cluster.log
|-- agent-ha-node
|   |-- mayastor-node1-loki-agent-ha-node.log
|   |-- mayastor-node1_mayastor-agent-ha-node-bcrqg
|   |   `-- agent-ha-node.log
|   |-- mayastor-node2-loki-agent-ha-node.log
|   |-- mayastor-node2_mayastor-agent-ha-node-wpsks
|   |   `-- agent-ha-node.log
|   |-- mayastor-node3-loki-agent-ha-node.log
|   |-- mayastor-node3_mayastor-agent-ha-node-cg5fh
|   |   `-- agent-ha-node.log
|   |-- mayastor-node4-loki-agent-ha-node.log
|   `-- …
```

feat(supportability): add flag to collect k8s logs with loki logs

---

call-home/src/common/constants.rs
call-home/src/main.rs
call-home/src/transmitter/client.rs

Cherry-pick PR #123

---

chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/templates/mayastor/agents/ha/ha-node-daemonset.yaml
chart/templates/mayastor/apis/api-rest-deployment.yaml
chart/templates/mayastor/csi/csi-controller-deployment.yaml
chart/templates/mayastor/csi/csi-node-daemonset.yaml
chart/templates/mayastor/io/io-engine-daemonset.yaml
chart/templates/mayastor/obs/obs-callhome-deployment.yaml
chart/templates/mayastor/operators/operator-diskpool-deployment.yaml
chart/values.yaml

Replace tag values with helm default function in deployment yamls.
These changes will handle repository specific tags implemented in main branch.

feat(chart): add repository specific tags as default image tag

---

.github/workflows/pr-commitlint.yml
.github/workflows/template-chart.yml
Jenkinsfile
chart/templates/_helpers.tpl
scripts/helm/shell.nix
scripts/helm/test-template.sh

fix(helm): incompatible types for comparison
---
ci: validate the default template
Adds test for jenkins and gha to ensure we don't submit an invalid template.

Fix helm template

---

k8s/upgrade/src/upgrade_resources/objects.rs

This replaces the core Events API with the events.k8s.io API

feat(upgrade): use events.k8s.io/v1 for Events

---

scripts/helm/publish-chart-yaml.sh
scripts/helm/test-publish-chart-yaml.sh

Allows a tag with a pre-release postfix of "%Y-%m-%d-%H-%M-%S"

feat: prepare chart scripts for the main branch

---

.github/workflows/develop-chart.yml

Main branch has been added to the "branches" section

chore(ci): add main branch to publish helm chart

---

.gitmodules
k8s/plugin/README.md
k8s/plugin/src/main.rs
k8s/plugin/src/resources/mod.rs

This brings the update to replica-topology.
Also update README file.

chore: update control-plane dependency

---

k8s/upgrade/src/constant.rs
k8s/upgrade/src/error.rs
k8s/upgrade/src/upgrade_resources/upgrade.rs

```
ashish@vm:~/code/rust/mayastor-extensions(upgrade-status)$ ./target/debug/kubectl-mayastor get upgrade-status
Upgrade From : 2.0.0
Upgrade To : 0.0.0
Upgrade Status : Upgrading Mayastor data-plane
```

feat(upgrade):  get upgrade status from events

---

k8s/upgrade-job/src/helm/chart.rs
k8s/upgrade-job/src/helm/values.rs
k8s/upgrade/src/constant.rs

- 6a47ad9bd5287dce2d6e97299003c1866bdbec9a

Cherry pick PR #164 to release/2.1 branch

---

k8s/upgrade-job/src/common/error.rs
k8s/upgrade-job/src/upgrade/data_plane.rs
k8s/upgrade-job/src/upgrade/utils.rs

- [7777f8b97dd4](https://github.com/openebs/mayastor-extensions/commit/7777f8b97dd404a374ce591087e4471304070e8b)

Cherry pick PR #167 to release/2.1 branch

---

k8s/plugin/src/main.rs
k8s/upgrade/src/preflight_validations.rs
k8s/upgrade/src/upgrade_resources/upgrade.rs
k8s/upgrade/src/user_prompt.rs

[be745d40e09c](https://github.com/openebs/mayastor-extensions/commit/be745d40e09caa0afceb8888a8055c34ecdcc643)

Cherry pick PR #174 to release/2.1 branch 

---

k8s/upgrade/src/upgrade_resources/objects.rs

- [57a15e925584](https://github.com/openebs/mayastor-extensions/commit/57a15e925584de4e51c4507f984a7b04740ba2bb)

Cherry pick PR #176 to release/2.1 branch 

---

.gitmodules

chore: point control-plane submodule to the right remote&commit

---

console-logger/src/console.rs
k8s/upgrade/src/error.rs
k8s/upgrade/src/preflight_validations.rs
k8s/upgrade/src/user_prompt.rs

the error is thrown and the pic displays the output of `$?` command

feat(upgrade): add error while validations in upgrade

---

console-logger/src/console.rs
k8s/upgrade/src/error.rs
k8s/upgrade/src/preflight_validations.rs
k8s/upgrade/src/user_prompt.rs

- [6415b162fca3](https://github.com/openebs/mayastor-extensions/commit/6415b162fca3dcf566b04eb496ea0e9d7b476391)

Cherry pick PR #182 to release/2.1 branch

---

k8s/upgrade/src/constant.rs
k8s/upgrade/src/error.rs
k8s/upgrade/src/upgrade_resources/objects.rs
k8s/upgrade/src/upgrade_resources/upgrade.rs

This generates the imagePullSecrets, imagePullPolicy, image registry for container image, instead of hard-coding them.

feat(k8s/upgrade): derive image properties for job image

---

chart/README.md
chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/values.yaml
k8s/upgrade-job/src/common/error.rs
k8s/upgrade-job/src/helm/chart.rs
k8s/upgrade-job/src/helm/values.rs
k8s/upgrade/src/constant.rs
k8s/upgrade/src/error.rs
k8s/upgrade/src/upgrade_resources/objects.rs
k8s/upgrade/src/upgrade_resources/upgrade.rs

This cherry-picks the following PR(s) into release/2.1 branch:
- #185 
- #186

Cherry-pick PRs #185 and #186 into release/2.1

---

k8s/upgrade-job/src/common/error.rs
k8s/upgrade-job/src/events/event_recorder.rs
k8s/upgrade-job/src/helm/client.rs

This PR cherry-picks the following PR commits:
- #165

Cherry-pick PR #165 to release/2.1

---

k8s/upgrade/src/upgrade_resources/upgrade.rs

- [083a63b145a6](https://github.com/openebs/mayastor-extensions/commit/083a63b145a63c3fd92dc516439b66c839500474)

Cherry pick PR #191 to release/2.1 branch

---

k8s/upgrade-job/src/upgrade/data_plane.rs

- [232c858418b6](https://github.com/openebs/mayastor-extensions/commit/232c858418b68ee803cd8554edc65ef7397926b1)

Cherry pick PR #195 to release/2.1 branch

---

k8s/upgrade-job/src/common/constants.rs
k8s/upgrade-job/src/common/error.rs
k8s/upgrade-job/src/events/event_recorder.rs
k8s/upgrade-job/src/helm/client.rs
k8s/upgrade-job/src/helm/upgrade.rs
k8s/upgrade-job/src/main.rs
k8s/upgrade-job/src/upgrade.rs
k8s/upgrade-job/src/upgrade/data_plane.rs
k8s/upgrade-job/src/upgrade/utils.rs

This PR cherry-picks the following PR(s) to release/2.1:
- #199

Cherry-pick PR #199 to release/2.1

---

exporter/src/pool/bin/main.rs
exporter/src/pool/client/pool.rs
exporter/src/pool/collector/pools_collector.rs

chore: update controller dependency
---
feat(exporter/diskpool): add committed size in bytes
This is useful for thin provisioning to determine if a pool is overcommitted.

Cherry-pick #197

---

k8s/upgrade-job/src/common/error.rs
k8s/upgrade-job/src/events/event_recorder.rs

Removed the acknowledgement channel. I don't know why I didn't see it straight away.... but, awaiting the task... to guarantee completion.

feat(upgrade-job): remove acknowledgement and just wait for task completion

---

k8s/upgrade-job/src/common/error.rs
k8s/upgrade-job/src/events/event_recorder.rs

This PR cherry-picks commits from the following PR(s) into release/2.1:
- #201

Cherry-pick #201 into release/2.1

---

k8s/upgrade-job/src/common/constants.rs
k8s/upgrade-job/src/common/error.rs
k8s/upgrade-job/src/helm/upgrade.rs
k8s/upgrade-job/src/helm/values.rs
k8s/upgrade-job/src/upgrade.rs
k8s/upgrade-job/src/upgrade/data_plane.rs
k8s/upgrade-job/src/upgrade/path.rs
k8s/upgrade-job/src/upgrade/utils.rs

This makes both control-plane (helm upgrade) and data-plane upgrade idempotent.

feat(upgrade-job): make upgrade idempotent

---

k8s/upgrade-job/src/common/constants.rs
k8s/upgrade-job/src/common/error.rs
k8s/upgrade-job/src/helm/upgrade.rs
k8s/upgrade-job/src/helm/values.rs
k8s/upgrade-job/src/upgrade.rs
k8s/upgrade-job/src/upgrade/data_plane.rs
k8s/upgrade-job/src/upgrade/path.rs
k8s/upgrade-job/src/upgrade/utils.rs

This PR cherry-picks the commits from the follow PR(s) into release/2.1 branch:
- #205

Cherry-pick PR #205 into release/2.1

---

k8s/supportability/src/collect/constants.rs
k8s/supportability/src/collect/logs/mod.rs
k8s/supportability/src/collect/system_dump.rs
k8s/upgrade/src/constant.rs

the system dump will also have the logs of upgrade pods

feat(supportability): add upgrade to supportability 

---

k8s/supportability/src/collect/constants.rs
k8s/supportability/src/collect/logs/mod.rs
k8s/supportability/src/collect/system_dump.rs
k8s/upgrade/src/constant.rs

- [5a407dda59fc](https://github.com/openebs/mayastor-extensions/commit/5a407dda59fc59e479c4a308826e191176bdc8cb)

Cherry pick PR #191 to release/2.1 branch 

---

chart/README.md
chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/templates/mayastor/agents/ha/ha-node-daemonset.yaml
chart/templates/mayastor/apis/api-rest-deployment.yaml
chart/templates/mayastor/csi/csi-controller-deployment.yaml
chart/templates/mayastor/csi/csi-node-daemonset.yaml
chart/templates/mayastor/io/io-engine-daemonset.yaml
chart/templates/mayastor/obs/obs-callhome-deployment.yaml
chart/templates/mayastor/operators/operator-diskpool-deployment.yaml
chart/values.yaml
k8s/upgrade-job/src/common/error.rs
k8s/upgrade-job/src/helm/chart.rs
k8s/upgrade-job/src/helm/values.rs

This PR cherry-picks the commits from the following PR into release/2.1:
- #210

Cherry-pick PR #210 to release/2.1 branch

---

.github/workflows/pr-submodule-branch.yml
.gitmodules
default.nix
nix/lib/version.nix
nix/overlay.nix
nix/pkgs/extensions/default.nix
scripts/git/set-submodule-branches.sh
scripts/nix/git-submodule-init.sh
scripts/release.sh

ci(gha/submodule): ensure submodules point to the right branch
Will help avoid mistakes if anyone uses update --remote...
---
build(images): add tag argument
Allows one to explicitly build the binaries with a given tag, as opposed to the alias-tag
which simply adds a docker image tag alias.

build: various improvements

---

Cargo.lock
k8s/plugin/src/main.rs
k8s/upgrade-job/src/helm/upgrade.rs
k8s/upgrade-job/src/opts/validators.rs
k8s/upgrade-job/src/upgrade/data_plane.rs
k8s/upgrade/Cargo.toml
k8s/upgrade/src/error.rs
k8s/upgrade/src/preflight_validations.rs
k8s/upgrade/src/upgrade_resources/upgrade.rs

the plugin code for upgrade was using `thiserror` , this has been changed to `snafu`.
The reason behind this is to merge upgrade-job  and upgrade crate to a single crate

feat(upgrade): change thiserror to snafu

---

chart/README.md
chart/templates/_helpers.tpl
chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/templates/mayastor/agents/ha/ha-node-daemonset.yaml
chart/templates/mayastor/apis/api-rest-deployment.yaml
chart/templates/mayastor/csi/csi-controller-deployment.yaml
chart/templates/mayastor/csi/csi-node-daemonset.yaml
chart/templates/mayastor/io/io-engine-daemonset.yaml
chart/templates/mayastor/obs/obs-callhome-deployment.yaml
chart/templates/mayastor/operators/operator-diskpool-deployment.yaml
chart/values.yaml

Resolves --> https://github.com/openebs/mayastor/issues/1365

chore: add tolerations to per component

---

README.md

We've already release v2 and provided an upgrade guide.

chore: remove breaking changes notice

---

Cargo.lock
k8s/plugin/src/main.rs
k8s/upgrade-job/src/common/constants.rs
k8s/upgrade-job/src/common/error.rs
k8s/upgrade-job/src/common/kube_client.rs
k8s/upgrade-job/src/helm/chart.rs
k8s/upgrade-job/src/helm/upgrade.rs
k8s/upgrade-job/src/helm/values.rs
k8s/upgrade-job/src/main.rs
k8s/upgrade-job/src/opts.rs
k8s/upgrade-job/src/opts/validators.rs
k8s/upgrade-job/src/upgrade.rs
k8s/upgrade-job/src/upgrade/path.rs
k8s/upgrade/src/constant.rs
k8s/upgrade/src/error.rs
k8s/upgrade/src/preflight_validations.rs
k8s/upgrade/src/user_prompt.rs
nix/pkgs/images/default.nix

This PR cherry-picks the following commit(s) to release/2.2:
- [0714118657e6](https://github.com/openebs/mayastor-extensions/commit/0714118657e6a87507ed80ecce98c2838153df79)
-  [a212687fcd81](https://github.com/openebs/mayastor-extensions/commit/a212687fcd816b77eab1459f23a9ec90c27cceb1)

Cherry pick PR #231 and #233 to release/2.2 branch 

---

chart/README.md
chart/crds/csi-volume-snapshot-class.yaml
chart/crds/csi-volume-snapshot-content.yaml
chart/crds/csi-volume-snapshot.yaml
chart/templates/mayastor/csi/csi-controller-deployment.yaml
chart/templates/mayastor/rbac/rbac.yaml
chart/values.yaml

- Adds VolumeSnapshot, VolumeSnapshotContent and VolumeSnapshotClass crds.
- Adds external-snapshotter and snapshot-controller as sidecar containers to csi-controller.
- Adds resource limit and requirements for snapshot-controller container.

feat(snapshots): add snapshot crds, snapshot-controller and external snapshotter side car containers.

---

k8s/plugin/README.md
k8s/plugin/src/main.rs
k8s/plugin/src/resources/mod.rs
k8s/supportability/src/lib.rs
k8s/upgrade/src/error.rs
k8s/upgrade/src/upgrade_resources/upgrade.rs
k8s/upgrade/src/user_prompt.rs

This PR cherry-picks the following commit(s) to release/2.2:
- [beb02c917776](https://github.com/openebs/mayastor-extensions/commit/beb02c91777604ad4175be0e872d0eb951bef2e2)
-  [8df03fc6dad8](https://github.com/openebs/mayastor-extensions/commit/8df03fc6dad8a5e8ae31ef69f578bb80af2d81e4)

Cherry pick PR #245 and  #247 to release/2.2 branch

---

chart/templates/mayastor/obs/obs-callhome-deployment.yaml
k8s/supportability/src/collect/constants.rs
k8s/supportability/src/collect/logs/mod.rs
k8s/supportability/src/collect/system_dump.rs

This PR adds the supportability feature for callhome pods.

feat(supportability): add supportability for call home

---

k8s/supportability/src/collect/logs/loki.rs
k8s/supportability/src/collect/system_dump.rs
k8s/supportability/src/lib.rs
k8s/supportability/src/operations.rs

265: fix(supportability/loki): add missing newlines r=tiagolobocastro a=tiagolobocastro
feat(supportability/loki): add loki dump subcommand

Cherry-pick pull request #265

---

k8s/upgrade/src/bin/upgrade-job/main.rs
k8s/upgrade/src/bin/upgrade-job/opts.rs

Adds version log when initializing.

feat(upgrade-job): add version info log

---

k8s/upgrade/src/bin/upgrade-job/common/error.rs
k8s/upgrade/src/bin/upgrade-job/common/kube_client.rs
k8s/upgrade/src/bin/upgrade-job/helm/client.rs
k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs
k8s/upgrade/src/bin/upgrade-job/upgrade.rs

This cherry-picks the commits from the following PR into release/2.3 branch:
- #281

Cherry-pick #281 into release/2.3

---

k8s/upgrade/src/bin/upgrade-job/common/error.rs
k8s/upgrade/src/bin/upgrade-job/common/kube_client.rs
k8s/upgrade/src/bin/upgrade-job/helm/client.rs
k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs
k8s/upgrade/src/bin/upgrade-job/upgrade.rs

The helm upgrade --install command doesn't actually install CRDs which are missing.
Changes:
- add CRD creation step before helm upgrade

feat(upgrade-job): install new CRDs

---

chart/README.md
chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/values.yaml
k8s/plugin/README.md

feat(snapshot/commitment): use commitment when creating a snapshot

Volume Snapshot Commitment

---

chart/README.md
chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/values.yaml
k8s/plugin/README.md

feat(snapshot/commitment): use commitment when creating a snapshot

Cherry-pick #288

---

.github/workflows/main-chart.yml

This step if done during github action will not cause any merge conflicts for Integration Point job

chore(ci): change loglevel to debug for all components

---

call-home/src/bin/callhome/collector/report_models.rs

The reports were coming like `created: Some(0)` .
So replaced `Option::is_none` with `is_zero` .

fix(eventing): remove some from created removed events

---

Cargo.lock
Cargo.toml
call-home/Cargo.toml
call-home/src/bin/stats/exporter/events_collector.rs
exporter/Cargo.toml
k8s/plugin/Cargo.toml
k8s/proxy/Cargo.toml
k8s/supportability/Cargo.toml
k8s/supportability/src/collect/logs/loki.rs
k8s/upgrade/Cargo.toml
k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs
k8s/upgrade/src/bin/upgrade-job/helm/yaml/yq.rs
k8s/upgrade/src/bin/upgrade-job/upgrade/path.rs
nix/lib/rust.nix
nix/sources.json

style: update with new clippy rules
---
build: upgrade cargo crate deps
---
build: upgrade nix and rust

Nix rust upgrade

---

.github/workflows/pull_request_template.md

Add PR template in extensions repo.

chore(upgrade): add pull request template for extensions

---

CONTRIBUTING.md

Remove missing docs link in contributing guide.
A more detailed build doc will be added at a later time.

docs: fix contributing guide

---

k8s/plugin/README.md
k8s/upgrade/src/bin/upgrade-job/upgrade/data_plane.rs
k8s/upgrade/src/bin/upgrade-job/upgrade/utils.rs
k8s/upgrade/src/plugin/upgrade.rs

This PR cherry-picks the following commit(s) to release/2.4:
- [667f40e6b89b](https://github.com/openebs/mayastor-extensions/commit/667f40e6b89b4a08f3e8c8390a2926ee6765872b)
-  [4101a29ce26f](https://github.com/openebs/mayastor-extensions/commit/4101a29ce26f7ad26799ad684016f6265d4c598e)

Cherry pick 314 316

---

k8s/upgrade/src/bin/upgrade-job/common/constants.rs
k8s/upgrade/src/bin/upgrade-job/common/error.rs
k8s/upgrade/src/bin/upgrade-job/events/event_recorder.rs
k8s/upgrade/src/bin/upgrade-job/helm/chart.rs
k8s/upgrade/src/bin/upgrade-job/helm/client.rs
k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs
k8s/upgrade/src/bin/upgrade-job/helm/values.rs
k8s/upgrade/src/bin/upgrade-job/helm/yaml/yq.rs
k8s/upgrade/src/bin/upgrade-job/opts/validators.rs
k8s/upgrade/src/bin/upgrade-job/upgrade.rs

This PR cherry-picks the commits from the following PR(s):
- #324
- #328

Cherry-pick PR #324 and #328 to release/2.4 branch

---

call-home/src/bin/callhome/main.rs
call-home/src/common/constants.rs
chart/templates/mayastor/obs/obs-callhome-deployment.yaml

This PR cherry-picks the commits from the following PR(s):
- #329

fix(eventing): enable stats container when eventing is enabled

---

k8s/upgrade/src/bin/upgrade-job/events/event_recorder.rs
k8s/upgrade/src/bin/upgrade-job/upgrade.rs

The upgrade job main thread starts a worker thread which listens for events and publishes them (as kubernetes events). When the upgrade method exits, the 'EventRecorder' instance for it is dropped. This in turn drops the event channel (used to pass events to the event worker) and also the handle to event worker. The event worker does not have enough time after the channel is dropped, to publish its events and exit. 
This PR defers all of the event publishes and actual upgrade steps to an inner function. The caller of this function makes sure the event loop exits before returning.

fix(upgrade-job): wait for event worker to exit for errors

---

k8s/upgrade/src/bin/upgrade-job/events/event_recorder.rs
k8s/upgrade/src/bin/upgrade-job/upgrade.rs

Cherry-picks the commits from the following PR(s) into release/2.4:
- #319

Cherry-pick PR #319 into release/2.4

---

k8s/upgrade/src/bin/upgrade-job/helm/values.rs
k8s/upgrade/src/bin/upgrade-job/helm/yaml/yq.rs

This PR cherry-picks the commits from the following PRs to release/2.4 branch:
- #334

Cherry-pick PR #334 to release/2.4 branch

---

k8s/upgrade/src/bin/upgrade-job/helm/chart.rs

This cherry-picks the commits from the following PRs(s):
- https://github.com/openebs/mayastor-extensions/pull/337

Cherry-pick #337 to release/2.4 branch

---

k8s/upgrade/src/bin/upgrade-job/upgrade/data_plane.rs
k8s/upgrade/src/bin/upgrade-job/upgrade/utils.rs

Check for volumes which are somehow only affected by the particular node which are we are trying to upgrade.
This for the volume rebuild validation , while upgrading the  io-engine pod , do the volume validation for only those volumes which are present of the node currently being upgraded.
This will make the upgrade faster , as it only checks for volume which are present of the io-engine node being upgraded .
No

chore(upgrade) : add volume node validation

---

nix/pkgs/images/default.nix

change contents to copyToRoot in nix file
While building the image ,the below warning was being thrown 
```
root@ashish-dev:~/code/rust/mayastor-extensions(develop)$ ./scripts/release.sh --image upgrade.job --alias-tag 2.5.0-alpha
trace: warning: in docker image openebs/mayastor-upgrade-job: The contents parameter is deprecated. Change to copyToRoot if the contents are designed to be copied to the root filesystem, such as when you use `buildEnv` or similar between contents and your packages. Use copyToRoot = buildEnv { ... }; or similar if you intend to add packages to /bin.
```
To remove the warning while build
No
Build succeds

change contents to copyToRoot

---

k8s/plugin/README.md
k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs
k8s/upgrade/src/bin/upgrade-job/opts.rs
k8s/upgrade/src/bin/upgrade-job/upgrade.rs
k8s/upgrade/src/plugin/constants.rs
k8s/upgrade/src/plugin/error.rs
k8s/upgrade/src/plugin/objects.rs
k8s/upgrade/src/plugin/upgrade.rs

Add `set-file` argument to upgrade
On the line of `set-args` the `set-file` can take the file as input.
You can use '--set-file' to set individual values from a file when the value itself is too long for the command line
No
Install and upgrade using the `set-file` command .

feat(upgrade): add set-file argument to upgrade

---

.github/workflows/develop-chart.yml
.github/workflows/main-chart.yml
.github/workflows/release-chart.yml

Changes:
- Update stefanprodan/helm-gh-pages from 1.5.0 to 1.7.0
- use OPENEBS_CI_GITHUB instead of GITHUB_TOKEN to push to openebs/mayastor-chart-donotuse.

fix(workflows/main_chart): update GitHub token secret

---

Cargo.lock
call-home/Cargo.toml
call-home/src/bin/callhome/collector/report_models.rs
call-home/src/bin/callhome/main.rs
call-home/src/bin/stats/cache.rs
call-home/src/bin/stats/cache/events_cache.rs
call-home/src/bin/stats/cache/nexus.rs
call-home/src/bin/stats/cache/pools.rs
call-home/src/bin/stats/cache/volume.rs
call-home/src/bin/stats/exporter/events_collector.rs
call-home/src/common/constants.rs
chart/templates/mayastor/io/io-engine-daemonset.yaml

Added nexus events to stats module.
Added nexus stats metrics to transmission module.
The nexus events added consists of creation, deletion counts, and rebuild begun and ended counts.
Manually tested.
Dependency on https://github.com/openebs/mayastor-control-plane/pull/673

feat(eventing): add nexus events to stats module

---

Cargo.lock
call-home/Cargo.toml
console-logger/Cargo.toml
exporter/Cargo.toml
k8s/plugin/Cargo.toml
k8s/proxy/Cargo.toml
k8s/supportability/Cargo.toml
k8s/supportability/src/collect/logs/k8s_log.rs
k8s/supportability/src/collect/logs/loki.rs
k8s/upgrade/Cargo.toml

Upgrade control-plane dep and cargo crates
Don't lag behind the control-plane.

build: upgrade cargo crates and ctrl-plane

---

chart/templates/_helpers.tpl

fix: remove invalid rebase characters from helpers

---

k8s/plugin/src/main.rs
k8s/supportability/src/collect/resource_dump.rs
k8s/supportability/src/collect/utils.rs
k8s/supportability/src/lib.rs

Namespace was not being taken from cli args when creating the rest client.

fix(kubectl-plugin): dump using non-default namespace

---

Cargo.lock
Cargo.toml
call-home/Cargo.toml
call-home/src/bin/stats/cache/events_cache.rs
metrics-exporter/Cargo.toml

Upgrade to latest controller and dependencies.
Upgrades tonic to the latest version.

chore: upgrade to latest controller deps

---

.github/workflows/release-binaries.yml

Adding to `Krew-index` requires a `LICENSE` file in the archive. 
See https://github.com/openebs/mayastor-extensions/pull/364#issuecomment-1791216672.
No.
Ran CI on my fork.

Add license to release binary archives

---

.github/workflows/publish-release-artifacts.yml
.github/workflows/staging-dco.yml
scripts/github/release-artifacts.sh

When a release is created, automatically download and upload artifacts to the release.
Publish artifacts to the release in their tar format.
Automatically add the release artifacts to the release.
Also ensures that the artifacts are uploaded as a tar file rather than a zip containing a tar.

ci: publish binaries on release

---

k8s/upgrade/src/plugin/upgrade.rs

Adds an option to specify the upgrade-job container registry. May be used to override the default behaviour of using the pre-existing Mayastor deployment's registry.
Closes https://github.com/openebs/mayastor/issues/1533
Adds the `--registry` option. This is optional. Example usage `kubectl mayastor upgrade --registry quay.io`.
Naah!

feat(upgrade): add option to specify upgrade job container registry

---

chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/templates/mayastor/rbac/rbac.yaml

- Add the HA_ENABLED env to core-agent with {{ .Values.agents.ha.enabled }}

feat(drain): add disable-ha arg to core-agent

---

chart/templates/mayastor/agents/core/agent-core-deployment.yaml
chart/templates/mayastor/agents/ha/ha-node-daemonset.yaml

Enables eventing in agent-ha-node and agent-ha-cluster.
Enables eventing to generate NvmePath events in agent-ha-node and HA events in agent-ha-cluster.
No
Manually tested.

feat(eventing): enable eventing in ha-cluster and ha-node agents

---

chart/Chart.yaml
chart/README.md

Bumps the dynamic-localpv-provisioner to its latest version

chore(chart): bump dynamic-localpv-provisioner

---

chart/Chart.yaml
chart/README.md

Cherry-picks the commits from the PRs:
- #388

chore(chart): bump dynamic-localpv-provisioner (#388)

---

chart/templates/_helpers.tpl
chart/templates/storageclass.yaml
chart/values.yaml
k8s/upgrade/src/bin/upgrade-job/helm/yaml/yq.rs
k8s/upgrade/src/plugin/preflight_validations.rs

This cherry-picks the commits from the following PRs:
- #391

Cherry-pick #391 to release/2.5 branch

---

chart/Chart.yaml
chart/README.md
chart/values.yaml

This change has an upgrade to loki-stack which seems to fail upgrades.
Reverting until more information is gathered.
todo: ensure we test upgrades on this CI and not only on e2e testing.
This change is required to get upgrades working again so close to the release.

Revert loki health targets check

---

scripts/github/release-artifacts.sh

Annotated tags need an extra deref to fetch the commit sha.
Ensures the publish of release artifacts works with an annotated tag.

ci(gha/release): download artifacts from annotated tags

---

Jenkinsfile
default.nix
nix/lib/sourcer.nix
nix/lib/version.nix
nix/overlay.nix
nix/pkgs/extensions/cargo-project.nix
nix/pkgs/extensions/default.nix
nix/pkgs/images/default.nix
scripts/release.sh

Uses the org of the remote git origin to set docker credentials and docker image org.

ci: use remote org for docker images

---

k8s/plugin/src/resources/mod.rs

Uncordon resource being passed for Uncrdon command

fix(uncordon): Rectify uncordon resource

---

Cargo.lock
shell.nix

Update ctrl dependency

---

.github/workflows/develop-to-release.yml
.github/workflows/helm-testing-chart.yml
.github/workflows/publish-release-artifacts.yml
scripts/helm/publish-chart-yaml.sh

Moves the action which publishes the helm-testing registry to its own file and break out of the previous main.
It seems the main had stop being published, so that will have to be re-enabled separately.

Helm Testing - develop support

---

Jenkinsfile

Removes stale slack notification.

ci: remove stale slack notification
