chart/templates/mayastor/io/io-engine-daemonset.yaml, chart/values.yaml
Add metrics polling interval as configurable parameter in [chart/values.yaml](https://github.com/openebs/mayastor-extensions/blob/develop/chart/values.yaml)
`metricsPollingInterval: "5m"`
By default, polling interval is five minutes.
=> chore: add metrics polling interval as configurable field in helm chart

chart/templates/mayastor/csi/csi-node-daemonset.yaml, chart/values.yaml
Make kubelet directory configurable.
This patch references to
https://github.com/canonical/mayastor-control-plane/commit/c87e2ed54471496ca1ff6fb65c2512212042e0d2
When running in microk8s needs to set kubeletDir as
kubeletDir: /var/snap/microk8s/common/var/lib/kubelet
This fix #5.
Signed-off-by: Xinliang Liu <xinliang.liu@linaro.org>
=> fix: fix run on microk8s

.github/bors.toml, chart/templates/mayastor/agents/agent-core-deployment.yaml, chart/templates/mayastor/apis/api-rest-deployment.yaml, chart/templates/mayastor/csi/csi-controller-deployment.yaml, chart/templates/mayastor/csi/csi-node-daemonset.yaml, chart/templates/mayastor/operators/operator-diskpool-deployment.yaml, chart/values.yaml, exporter/src/bin/pool/main.rs, nix/lib/rust.nix, nix/lib/version.nix, nix/sources.json, rpc/src/lib.rs
chore(nix): upgrade to release channel
Also pin the rust nightly to the same day as the control-plane.
---
chore: use silence log env variable for control-plane components
Use the env var RUST_LOG_SILENCE which silences overly verbose components.
By default we use whatever is set during compile time.
A common base.logSilenceLevel is added to set a common silence for all components but each
component can also override it.
=> chore: use silence log env variable for control-plane components

chart/templates/mayastor/io/io-engine-daemonset.yaml
This will be changed to v1 when the control-plane supports v1.
=> chore: temporarily pin io-engine api-version to v0

.pre-commit-config.yaml, chart/values.yaml, shell.nix
chore: remove node ports
Our kubectl-plugin no longer needs node ports to reach our services.
---
chore: temporarily pin io-engine to v0
This will be changed to v1 when the control-plane supports v1.
---
fix: run pre-commit hooks under the nix-shell
=> chore: remove node ports

.github/workflows/release-chart.yaml, chart/Chart.yaml
Adds the release workflow and set the mayastor version to 2.0.0-develop.
=> chore: add gh action to release helm chart as a gh-page

chart/templates/mayastor/agents/agent-core-deployment.yaml
Required after https://github.com/openebs/mayastor-control-plane/pull/322
=> fix: use core agent server endpoint as socket

call-home/src/common/constants.rs, call-home/src/main.rs, call-home/src/transmitter/encryption.rs
This PR fixes the default encrytion dir path for the gpg command. The directory path used in the default constant must not have a trailing slash.
=> fix(call-home): fix path join for output_filepath var

call-home/src/common/constants.rs, call-home/src/common/errors.rs, call-home/src/main.rs, call-home/src/transmitter/encryption.rs
This PR uses the PathBuf type instead of the String type for filepaths. It is idiomatic to use PathBuf for paths.
=> refactor(call-home): use PathBuf instead of String for paths

call-home/src/main.rs
This fixes a bug introduced in 5f93adc08974dcbaa3a06722066baa258eb94e43. The k8s_cluster_id variable has to be a hashed value by design.
=> fix(call-home): add hashing for the k8s_cluster_id

.github/workflows/release-chart.yaml, Jenkinsfile, chart/Chart.yaml, chart/templates/NOTES.txt, chart/values.yaml, scripts/helm/publish-chart-yaml.sh, scripts/helm/shell.nix, scripts/helm/test-publish-chart-yaml.sh, scripts/release.sh, shell.nix
This is an interim solution for this next release until we sort out what the automated procedure will be like.
We'll keep the the versions and images pointing to the v2.0.0 release, so the chart will not be working from the git repo as is, without overriding the image tags.
When a new tag is pushed (eg: 2.0.0-alpha.2), we publish a helm chart with that semver for the appVersion and for the version. Exception: if the version has already increased, we'll simply bump the version.
A test has been added which shows how this works.
=> feat(publish-tag): publish the helm chart on tag push

chart/templates/mayastor/agents/core/agent-core-and-ha-cluster-deployment.yaml, chart/templates/mayastor/agents/core/agent-core-deployment.yaml, chart/templates/mayastor/agents/core/agent-core-service.yaml, chart/values.yaml
HA cluster agent is added as a separate new container to the `agent-core` deployment since cluster agents depends on core-agent for its working and hence should have the dynamic behaviour as that of the core-agent. Therefore instead of adding `ha-cluster-agent` as a separate deployment, it is added alongside `core-agent`.
Signed-off-by: Abhishek Agarwal <abhishek.agarwal@mayadata.io>
=> feat(ha-cluster-agent): added helm template for ha cluster agent

default.nix, nix/overlay.nix, nix/pkgs/images/default.nix
This PR adds the img_tag argument to nix build, this enables the --alias-tag flag that was added in the PR https://github.com/openebs/mayastor-extensions/pull/45.
Additionally this also updates the gitmodule dependencies.
This PR's commits should not be squashed, the gitmodules should be a separate commit, so that the changes to the build may be cherry-picked into release/2.0 branch.
=> chore(ci): add img_tag arg to nix build

.gitignore, chart/templates/mayastor/io/io-engine-daemonset.yaml
This PR sets the `spec.updateStrategy` on the io-engine DaemonSet to OnDelete. This is required for releases beyond 2.0 when we want to have granular control over the delete sequence of the Mayastor data plane components. This, together with Nexus HA, opens up the possibility for upgrade with live volumes.
=> feat(upgrade): set io-engine DaemonSet to use OnDelete updateStrategy

chart/values.yaml
Add compaction after 100 revisions.
Set space quota to 8GiB to prevent the keyspace from growing excessively large.
=> chore(etcd/compaction): enable compaction by default

.github/workflows/release-binaries.yml, Jenkinsfile, call-home/src/main.rs, default.nix, k8s/plugin/Cargo.toml, k8s/proxy/src/proxy.rs, nix/pkgs/extensions/cargo-project.nix, nix/pkgs/images/default.nix, nix/pkgs/utils/default.nix, operators/src/upgrade/config.rs, shell.nix
fix: make darwin images statically linked
Openssl and libiconv were dynamically linked, which won't work... as they were pointing
to the nix store path.
Sadly on darwin pkgsStatic is not really static:
https://github.com/NixOS/nixpkgs/issues/120862
So we have to build our own static openssl and libiconv, which can take sometime.
todo: use cachix to speed up most builds.
---
feat(nix-shell): add support for aarch64-darwin
=> fix: make darwin images statically linked

k8s/plugin/src/constant.rs, k8s/plugin/src/resources/objects.rs, k8s/plugin/src/resources/upgrade.rs
As suggested by @tiagolobocastro , we nee to read the release name present as  label `helm-release` and use that name to create the upgarde resources.
I just used `ashish` and release name and the o/p looks like 
```
NAME                                       READY   STATUS    RESTARTS   AGE
ashish-agent-core-79cd9d4747-jwh6s         2/2     Running   0          11m
ashish-agent-ha-node-mv65c                 1/1     Running   0          11m
ashish-agent-ha-node-tdgtk                 1/1     Running   0          11m
ashish-agent-ha-node-z857z                 1/1     Running   0          11m
ashish-api-rest-5675f5767d-pc6zv           1/1     Running   0          11m
ashish-csi-controller-f84cd68f4-kvf5q      3/3     Running   0          11m
ashish-csi-node-q7wh7                      2/2 …
```
=> feat(upgrade): fetch and use release name for upgrade components

chart/templates/mayastor/io/io-engine-daemonset.yaml, chart/values.yaml
Modify io-engine-daemonset.yaml to optionally add the
reactor freeze detection command line argument
for mayastor io-engine
=> chore: add config for reactor freeze detection

Jenkinsfile
With so many builds it takes ever more to get free agents. todo: add more build agents?
=> ci: bump timeout to 2 hours

Cargo.lock, k8s/plugin/src/constant.rs, k8s/plugin/src/resources/objects.rs, k8s/plugin/src/resources/uo_client.rs, k8s/plugin/src/resources/upgrade.rs, operators/Cargo.toml, operators/src/upgrade/bin/main.rs, operators/src/upgrade/common/error.rs, operators/src/upgrade/config.rs, operators/src/upgrade/controller/mod.rs, operators/src/upgrade/controller/reconciler.rs, operators/src/upgrade/controller/utils.rs, operators/src/upgrade/helm/client.rs, operators/src/upgrade/k8s/client.rs, operators/src/upgrade/k8s/crd/v0.rs, operators/src/upgrade/phases/preflight.rs, operators/src/upgrade/phases/updating.rs, operators/src/upgrade/rest/service.rs
Upgrade operator changes:
- run controller asynchronously/respond to apply upgrade REST call
- add check to see if the io-engine pods all come to running state after upgrade
- add check to verify if all volumes are unpublished before restarting io-engine
- add loop to retry data-plane upgrade
- add check to verify if io-engine pods are restarted
Kubectl plugin changes:
- update upgrade operator deployment args flags
- add get, list, create, delete, patch permissions for poddisruptionbudget resource
=> feat(upgrade): refactor upgrade controller and kubectl plugin

chart/templates/mayastor/agents/core/agent-core-deployment.yaml, chart/templates/mayastor/agents/core/agent-core-service.yaml, chart/templates/mayastor/agents/ha/ha-node-daemonset.yaml, chart/templates/mayastor/apis/api-rest-deployment.yaml, chart/templates/mayastor/apis/api-rest-service.yaml, chart/templates/mayastor/csi/csi-controller-deployment.yaml, chart/templates/mayastor/csi/csi-node-daemonset.yaml, chart/templates/mayastor/io/io-engine-daemonset.yaml, chart/templates/mayastor/metrics/metrics-exporter-pool-service.yaml, chart/templates/mayastor/obs/obs-callhome-deployment.yaml, chart/templates/mayastor/operators/operator-diskpool-deployment.yaml
**Why is this change required?**
v1.LabelSelectors cannot be patched during helm upgrade, hence it should only carry labels which don't change across helm chart versions.
=> fix(upgrade): remove labels carrying the chart version from LabelSelectors for Services, Deployments, DaemonSets, StatefulSets

k8s/plugin/src/resources/objects.rs
This is required by the upgrade-operator container to upgrade to the changes in...
- #105 
=> feat(upgrade): update upgrade-operator RBAC

chart/README.md, chart/values.yaml
Changes:
- Raise memory limit for agent-core container to 128MiB
- Raise memory request for agent-core container to 32MiB
- Raise memory limit for HA cluster agent to 64MiB
=> chore(chart): raise memory limits for agent-core and agent-ha-cluster

Cargo.lock, call-home/Cargo.toml, call-home/src/common/constants.rs, call-home/src/main.rs, call-home/src/transmitter/client.rs
This change uses the version_info crate from the openebs/mayastor-dependencies repo (via dependencies/control-plane git submodule's dependency) to generate the version for the call-home payload and the HTTP header.
This uses the git tag, if present, otherwise defaults to the commit hash for the HEAD commit of the repo branch.
=> feat(call-home): use version_info crate to generate git version

chart/values.yaml, scripts/helm/publish-chart-yaml.sh, scripts/helm/test-publish-chart-yaml.sh
style: remove spaces for etcd port within init containers
This should help fix linter errors on openebs/charts
---
ci: allow patch version different when publishing
This will allows to publish 2.0.x where x > 0
TODO: add check for previous tag so we can restrict to bumps of 1 as otherwise
the current script would allows us to publish v2.0.9 for example!
=> ci: allow patch version different when publishing

chart/values.yaml, scripts/helm/publish-chart-yaml.sh, scripts/helm/test-publish-chart-yaml.sh
style: remove spaces for etcd port within init containers
This should help fix linter errors on openebs/charts
---
ci: allow patch version different when publishing
This will allows to publish 2.0.x where x > 0
TODO: add check for previous tag so we can restrict to bumps of 1 as otherwise
the current script would allows us to publish v2.0.9 for example!
=> Cherry-pick #133 into develop

console-logger/src/console.rs, k8s/plugin/src/main.rs, k8s/upgrade/src/constant.rs, k8s/upgrade/src/lib.rs, k8s/upgrade/src/preflight_validations.rs, k8s/upgrade/src/upgrade_lib.rs, k8s/upgrade/src/upgrade_resources/upgrade.rs, k8s/upgrade/src/user_prompt.rs, operators/src/upgrade/controller/reconciler.rs
The o/p of kubeclt-mayastor upgrade
``` 
ashish@vm:~/code/rust/mayastor-extensions(single-replica)$ ./target/debug/kubectl-mayastor  upgrade
Volumes which make use of a single volume replica instance will be unavailable for some time during upgrade.
It is recommended that you do not create new volumes which make use of only one volume replica.
Below are the list of cordoned nodes. Since there are some cordoned nodes,
the rebuild will happen on another nodes so please have enough available free space or else the rebuild will get stuck forever.
node-0-64716
The list below shows the single replica volumes in cluster.
These single replica volumes may not be accessible during upgrade.
To skip this validation, please retry  with '--skip-single-replica-volume-validation` flag.
ms-volume-claim …
```
=> feat(upgrade): list single volume replica before upgrade

chart/README.md, chart/templates/_helpers.tpl, chart/templates/mayastor/csi/csi-node-daemonset.yaml, chart/templates/mayastor/io/io-engine-daemonset.yaml, chart/values.yaml
Allows specifying the exact list of cores.
Examples:
--set='io_engine.coreList=1'
--set='io_engine.coreList={1,2,3}'
Also adds validation to ensure the coreCount is always >= 1 and all cores are unique.
=> Add core list variable

k8s/upgrade/src/upgrade_resources/objects.rs, k8s/upgrade/src/upgrade_resources/upgrade.rs
The kubectl-mayastor tool receives the optional flag `--skip-data-plane-restart` as an option to the upgrade subcommand. This flag currently incorrectly enables data-plane restart. This PR uses the value from the same flag and passes it to the upgrade Kubernetes Job verbatim.
Additionally, the flag is made optional for the Job, and only passed in if it is enabled. This is done because Clap v4's derive API cannot interpret string literals as bool inputs to flags.
=> fix(plugin/upgrade): pass on --skip-data-plane-restart flag to upgrade

chart/README.md, chart/templates/_helpers.tpl, chart/templates/mayastor/csi/csi-node-daemonset.yaml, chart/templates/mayastor/io/io-engine-daemonset.yaml, chart/values.yaml
Allows specifying the exact list of cores.
Examples:
--set='io_engine.coreList=1'
--set='io_engine.coreList={1,2,3}'
Also adds validation to ensure the coreCount is always >= 1 and all cores are unique.
=> feat(io-engine/cores): add missing core list

console-logger/src/console.rs, k8s/plugin/src/main.rs, k8s/upgrade/src/constant.rs, k8s/upgrade/src/lib.rs, k8s/upgrade/src/preflight_validations.rs, k8s/upgrade/src/upgrade_resources/upgrade.rs, k8s/upgrade/src/user_prompt.rs
The op is shown as 
```
ashish@vm:~/code/rust/mayastor-extensions(dry-run)$ ./target/debug/kubectl-mayastor  upgrade --dry-run
Volumes which make use of a single volume replica instance will be unavailable for some time during upgrade.
It is recommended that you do not create new volumes which make use of only one volume replica.
List of control plane pods which will be restarted during upgrade.
mayastor-agent-core-f5978cfdc-6sz7q
mayastor-api-rest-744d8f54bc-xr7gk
List of data plane pods which will be restarted during upgrade.
mayastor-io-engine-49xwm
mayastor-io-engine-bwtn6
mayastor-io-engine-d7v7v
Finally the cluster deployment will be upgrade to version: "develop"
```
and 
```
ashish@vm:~/code/rust/mayastor-extensions(dry-run)$ ./target/debug/kubectl-mayastor  upgrade --dry-run …
```
=> add list of pods in dry run flag 

nix/pkgs/extensions/cargo-project.nix, nix/pkgs/images/default.nix, scripts/helm/publish-chart-yaml.sh
As things stand the tree is always pointing to the stable helm version, eg: 2.1.0 
When building upgrade images for pre-releases or patches we need to patch the chart so that it may point to the correct version.
This is done using the same publish script that is used to publish the chart to the helm repo.
If we're building without a tag then for now we simply ignore this..
=> build(helm/upgrade): prepare chart before packing container

k8s/upgrade-job/src/helm/chart.rs, k8s/upgrade-job/src/helm/values.rs, k8s/upgrade/src/constant.rs
This is required because the helm template function 'default' uses the values set in image.repoTags.* keys. Leaving it empty while using the '--reuse-values' flag will result in a nil pointer error in helm.
Adds an extra `--set` flag to the umbrella chart `helm upgrade command` to update the release.version (e.g. https://github.com/openebs/charts/blob/main/charts/openebs/values.yaml#L21)
=> fix(upgrade-job): add  '--set' options for image.repoTags options

k8s/upgrade/src/upgrade_resources/objects.rs
This PR adds some rbac role to cluster role as  we got an rbac issue when tried to run on ci-cd pipeline. This  issue was not faced when i ran manually on hetzner.
The issue faced was 
`Error: UPGRADE FAILED: could not get information about the resource: persistentvolumes \"etcd-volume-0\" is forbidden: User \"system:serviceaccount:mayastor:mayastor-upgrade-service-account-develop\" cannot get resource \"persistentvolumes\" in API group \"\" at the cluster scope\n"}`
=> feat(upgrade): add rbac role and edit cordoned node message

k8s/upgrade-job/src/common/constants.rs, k8s/upgrade-job/src/common/error.rs, k8s/upgrade-job/src/helm/upgrade.rs, k8s/upgrade-job/src/upgrade.rs, k8s/upgrade-job/src/upgrade/data_plane.rs, k8s/upgrade-job/src/upgrade/utils.rs
- add 'wait forever' retry logic for long running tasks
- use field-selector for picking out io-engine pods belonging to a specific node
- add a check for control-plane health before starting out with data-plane upgrade
- handle cases for node drain failure: drain label already exists, check drain status for upgrade-specific drain label and cordon label
- handle case for node uncordon failure: avoid uncordon if uncordon label does not exist
- Add event to mark the start of the upgrade
- Added and modified log messages for data plane
- Added a failure case for when the to_version and the from_version are the same.
=> fix(upgrade-job): refactor data-plane upgrade

chart/README.md, chart/templates/mayastor/agents/core/agent-core-deployment.yaml, chart/values.yaml, k8s/upgrade-job/src/common/error.rs, k8s/upgrade-job/src/helm/chart.rs, k8s/upgrade-job/src/helm/values.rs, k8s/upgrade/src/upgrade_resources/objects.rs
This adds '--set' flags for thin_provisioning helm chart options. These are required because these are not present in 2.0.x helm charts, and a `helm upgrade` command along with the `--reuse-values` flag wil result in a nil pointer error for the helm binary.
=> fix(upgrade-job): add '--set' flags for thin provisioning

k8s/upgrade-job/src/common/error.rs, k8s/upgrade-job/src/events/event_recorder.rs, k8s/upgrade-job/src/helm/client.rs
This includes this behavior:
- Events are now published from a separate tokio::task.
- Events are now re-published every 20 min, if no new event is generated. This let's a user probe for the latest event, in case an event is lost to the k8s events' expiration duration of 1 hour.
Also increases helm upgrade timeout to 15 min (from the default 5m).
Also, removes some unused errors and fixes serde container attribute for renaming struct members to camelCase.
P. S.: I deleted the Cargo.lock and regenerated it with `cargo build`.
=> feat(upgrade-job): support for continuous eventing for the upgrade duration

k8s/upgrade/src/constant.rs
This change was brought in when cherry-picking the k8s/upgrade crate from the develop branch.
=> feat(k8s/upgrade): use release-2.1 tagged upgrade image on the release/2.1 branch

k8s/upgrade/src/constant.rs
This mirrors the changes from #189 for the image tag variable name and the doc comment above it.
=> fix(k8s/upgrade): rename image tag variable

k8s/upgrade/src/upgrade_resources/upgrade.rs
This error was introduced as some code was modified in PR #165  for serialisation of events.
=> feat(upgrade): resolve deserialisation error in get upgrade status

k8s/upgrade/src/constant.rs, k8s/upgrade/src/upgrade_resources/upgrade.rs
Since the image tag was modified to append to upgrade resource names , the image in pod was wrong. as below
`docker.io/openebs/mayastor-upgrade-job:vv2-1-0`
This PR resolves this problem
Even the upgrade resources had the name like `mayastor-upgrade-role-vv2-1-0` , this is also resolved to `mayastor-upgrade-role-v2-1-0`
=> feat(upgrade): rectify image tag

k8s/upgrade-job/src/common/constants.rs, k8s/upgrade-job/src/common/error.rs, k8s/upgrade-job/src/events/event_recorder.rs, k8s/upgrade-job/src/helm/client.rs, k8s/upgrade-job/src/helm/upgrade.rs, k8s/upgrade-job/src/main.rs, k8s/upgrade-job/src/upgrade.rs, k8s/upgrade-job/src/upgrade/data_plane.rs, k8s/upgrade-job/src/upgrade/utils.rs
Presently, the drop implementation for EventRecorder cancels the event loop task before all of the events could be pulished. This change adds a channel to receive an acknowledgement message, after closing the primary event channel.
No cancellation is done, the worker should exit on the next line after the acknowledgement.
Additionally, adds/modifies some logs.
=> feat(k8s/upgrade-job): add wait for all event-publishes 

exporter/src/pool/bin/main.rs, exporter/src/pool/client/pool.rs, exporter/src/pool/collector/pools_collector.rs
chore: update controller dependency
---
feat(exporter/diskpool): add committed size in bytes
This is useful for thin provisioning to determine if a pool is overcommitted.
=> DiskPool Metrics Exporter - add committed size in bytes

chart/templates/mayastor/csi/csi-controller-deployment.yaml
`--extra-create-metadata`: Enables the injection of extra PVC and PV metadata as parameters when calling `CreateVolume` on the driver (keys: `"csi.storage.k8s.io/pvc/name"`, `"csi.storage.k8s.io/pvc/namespace"`, `"csi.storage.k8s.io/pv/name"`). 
This is needed for generating the unique name for the `volume group`. If this is not enabled for whatever reason, we would not trigger `volume group feature` and `would just warn and continue` with normal creation process.
=> feat(volume group): enable extra create metadata injection by csi-provisioner

.github/workflows/release-binaries.yml
Not quite sure why this started failing.. anyways updating nix action to 20 fixes it.
=> ci(gha): update nix action to v20

.github/workflows/release-binaries.yml
Tag was not being included on kubectl-binary which causes upgrade to deploy job container using branch rather than the release tag.
=> fix(gha/binaries): build on tag push

Cargo.lock, k8s/upgrade-job/src/common/constants.rs, k8s/upgrade-job/src/common/error.rs, k8s/upgrade-job/src/common/kube_client.rs, k8s/upgrade-job/src/helm/chart.rs, k8s/upgrade-job/src/helm/upgrade.rs, k8s/upgrade-job/src/helm/values.rs, k8s/upgrade-job/src/main.rs, k8s/upgrade-job/src/opts.rs, k8s/upgrade-job/src/opts/validators.rs, k8s/upgrade-job/src/upgrade.rs, k8s/upgrade-job/src/upgrade/path.rs
- remove support for upgrade for the openebs/openebs helm chart:
Previously the upgrade-job was outfitted with the tools to upgrade the
openebs/openebs helm chart. However, the upgrade assumed that the helm
chart only made use of mayastor and no other storage engine. This is a
convenient feature, until one of the other openebs/openebs subcharts
is upgraded. Then this openebs/openebs upgrade via this upgrade-job is
insufficient, as it only concerns itself with the changes of the mayastor
subchart. As an alternative, the upgrade documentation at openebs.io/docs
will furnish the instructions to enable a user to carry out the mayastor
upgrade alongside any other upgrade that the particular openebs/openebs
might require. The user is to upgrade the openebs/openebs helm chart, and
iff he has …
=> feat(upgrade-job): support for upgrade to openebs-3.7.0

k8s/plugin/src/main.rs, k8s/upgrade-job/src/common/error.rs, k8s/upgrade-job/src/helm/upgrade.rs, k8s/upgrade-job/src/opts.rs, k8s/upgrade-job/src/upgrade.rs, k8s/upgrade-job/src/upgrade/path.rs, k8s/upgrade/src/constant.rs, k8s/upgrade/src/error.rs, k8s/upgrade/src/preflight_validations.rs, k8s/upgrade/src/user_prompt.rs, nix/pkgs/images/default.nix
The `unsupported_versions.yaml` file was read using the std::current_dir(). This lead to the problem where in the file was not present in nix-build environment. 
This PR modifies the code to read the file at compile time only .
=> feat(upgrade): read unsupported versions yaml file at compile time

k8s/upgrade-job/src/common/error.rs, k8s/upgrade-job/src/helm/upgrade.rs, k8s/upgrade-job/src/upgrade/path.rs
- add failure case for when the source version is newer than the target version
- remove redundant check for 'already_upgraded' case: currently the invalid versions are explicitly listed in an input YAML file, thus there need not be an additional exclusion case here, as we do not list the current version in the invalid-versions-file
=> fix(upgrade-job): refactor version check

k8s/upgrade-job/src/common/constants.rs, k8s/upgrade-job/src/helm/upgrade.rs, k8s/upgrade-job/src/helm/values.rs
- use `--set` flags to set thin provisioning flags for 2.0.x releases, instead of 2.1.x release.
- allow 'no-rollback' rule to be overridden by the `--skip-upgrade-path-validation` flag. This is not necessary for the openebs/openebs (Umbrella) chart because this upgrade-job does not support upgrade for the openebs chart, so might as well move that check to be a Core chart exclusive check.
- allow the `--set` flags for 2.0.x release to be used with future 2.0.x releases as well, and not just till 2.0.1.
=> fix(upgrade-job): upgrade path validation and set flags

chart/Chart.yaml, chart/README.md, chart/values.yaml
A per the suggestion here `IMHO we should disable it if either callhome or "eventing" is disabled.` 
I tried to tweak the condition like `condition: obs.callhome.enabled and nats.enabled` , but this doesn't work.
Helm does not support the `and ` in conditions . The max is does is an `OR` condition using comma  like `condition: obs.callhome.enabled, nats.enabled`.  Only the first valid path found in the list is evaluated .
Thus enabling nats only when the call home is enabled.
**Refer**
- [Link 1](https://stackoverflow.com/questions/75649506/how-to-add-multiple-conditions-check-in-global-charts-file-in-helm)
- [Link 2](https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies)
=> fix(callhome) : apply nats when callhome is enabled

.github/workflows/release-binaries.yml
Add `fetch-depth` to fetch all history for tags.
=> ci(gha): fix missing tag in kubectl binary

nix/lib/version.nix, nix/pkgs/extensions/cargo-project.nix, nix/pkgs/images/default.nix
Jenkins CI uses '@' in its workspace directory name. Nix seems to not like that. builtins.path { name = ... } lets you choose the directory name when copying the source files to the nix store directory.
=> fix(nix): use builtins.path instead of builtins.filterSource

k8s/upgrade/src/bin/upgrade-job/common/constants.rs, k8s/upgrade/src/bin/upgrade-job/common/error.rs, k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs
E2e tests may use helm chart versions which do not conform to the release/pre-release patterns. While most tests don't require this, as we do not validate the version string pattern for the helm chart in the container, restarts after the helm upgrade stage (control plane upgrade) position the target chart as the source chart, and that goes through validation.
This regex change allows e2e test tags to be pass the validation.
=> feat(upgrade-job): recognise flexible testing versions for helm charts

k8s/upgrade/src/bin/upgrade-job/helm/client.rs
The upgrade-job issues a helm upgrade command which in itself does not install CRDs. The changes for release v2.3.0 introduces the snapshot CRDs to the mayastor helm chart. Using the --install flag will add it into the upgrade template if it is missing from the cluster
=> fix(upgrade-job): use '--install' flag with helm upgrade

k8s/supportability/src/collect/logs/loki.rs, k8s/supportability/src/collect/system_dump.rs, k8s/supportability/src/lib.rs, k8s/supportability/src/operations.rs
feat(supportability/loki): add loki dump subcommand
---
fix(supportability/loki): add missing newlines
It's not entirely clear how this was even working before, but this should work going forward.
=> fix(supportability/loki): add missing newlines

chart/values.yaml
Since eventing feature is pushed for next release, disabling this feature for 2.3 release.
cc @avishnu
=> feat(eventing): disable eventing for release 2.3

Cargo.lock, k8s/plugin/README.md, k8s/supportability/Cargo.toml, k8s/supportability/src/collect/common.rs, k8s/supportability/src/collect/k8s_resources/client.rs, k8s/supportability/src/collect/k8s_resources/k8s_resource_dump.rs, k8s/supportability/src/collect/resource_dump.rs, k8s/supportability/src/collect/resources/mod.rs, k8s/supportability/src/collect/resources/node.rs, k8s/supportability/src/collect/resources/pool.rs, k8s/supportability/src/collect/resources/snapshot.rs, k8s/supportability/src/collect/resources/traits.rs, k8s/supportability/src/collect/resources/utils.rs, k8s/supportability/src/collect/resources/volume.rs, k8s/supportability/src/collect/system_dump.rs, k8s/supportability/src/lib.rs, k8s/supportability/src/operations.rs
- Add VolumeSnapshot and VolumeSnapshotContent CRs for mayastor driver.
- Add Rest api snapshot resources to topology.
- Add Rebuild history to the volume.
- Remove dead code and crate.
- Hide resource level dump commands, until further refactor.
=> chore: add snasphot and rebuild history to bundle, disable resouce level dump

k8s/plugin/src/main.rs, k8s/upgrade/src/bin/upgrade-job/common/error.rs, k8s/upgrade/src/bin/upgrade-job/events/event_recorder.rs, k8s/upgrade/src/bin/upgrade-job/helm/client.rs, k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs, k8s/upgrade/src/bin/upgrade-job/opts.rs, k8s/upgrade/src/bin/upgrade-job/upgrade.rs, k8s/upgrade/src/plugin/constants.rs, k8s/upgrade/src/plugin/error.rs, k8s/upgrade/src/plugin/objects.rs, k8s/upgrade/src/plugin/preflight_validations.rs, k8s/upgrade/src/plugin/upgrade.rs, k8s/upgrade/src/plugin/user_prompt.rs
Helm doesn't validates the  value passed 
Example 
```
root@ashish-dev:~/code/rust/mayastor-extensions(set-flag)$ helm install mayastor mayastor/mayastor -n mayastor --create-namespace --version 2.3.0 --set='alpha=beta,gamma={30,101}'
NAME: mayastor
LAST DEPLOYED: Wed Aug  9 06:26:30 2023
NAMESPACE: mayastor
STATUS: deployed
REVISION: 1
NOTES:
OpenEBS Mayastor has been installed. Check its status by running:
$ kubectl get pods -n mayastor
```
Upon getting the values 
```
root@ashish-dev:~/code/rust/mayastor-extensions(set-flag)$ helm get values mayastor --all  -n mayastor  -oyaml > ~/test.yaml
```
The values present in `test.yaml` 
```
root@ashish-dev:~$ grep -i alpha  test.yaml
alpha: beta
root@ashish-dev:~$ grep -i -C 4 gamma  test.yaml
limits: {}
requests: {}
eventing:
enabled: false …
```
=> feat(upgrade): add set flag in upgrade

k8s/plugin/README.md, k8s/upgrade/src/plugin/upgrade.rs
Update upgrade docs.
Add `set-args` to upgrade docs and remove the _capital_ aliases for `skip-data-plane-restart` , `skip-single-replica-volume-validation`, `skip-replica-rebuild`, `skip-cordoned-node-validation` to make it consistent with helm command 
The helm command doesn't have any capital alias.
In case the user sets any value using --set-args flag at the time of install. The upgrade might override those values. 
So in order to keep the user values intact the user have to pass the `--set-args ` while upgrade.
Like `kubectl-mayastor upgrade --set-args obs.callhome.enabled=false`
No. This is just a docs update , The feature was in PR #307 
1. Install mayastor 
```
helm install mayastor mayastor/mayastor -n mayastor --set obs.callhome.enabled=false --create-namespace --version 2.3.0 …
```
=> chore(upgrade): update upgrade docs

k8s/upgrade/src/bin/upgrade-job/upgrade/data_plane.rs, k8s/upgrade/src/bin/upgrade-job/upgrade/utils.rs
After the addition of partial rebuild, the rebuild validations has been changed for upgrade.
The logic to check if any rebuild is in progress has been changed. 
The new rebuild validation is based on the logic below.
1.   _If all the volumes are online (across the cluster) then continue with upgrade_ 
2.  _In case of volumes which are degraded/faulted check for replica rebuild in progress_
-  If replica rebuild in progress then wait for rebuild to complete 	
- If no replica rebuild in progress then step wait for a period of 10+ minutes with an interval of 35 seconds. At every interval check for replica rebuild in progress, If rebuilding then wait , else after 10 minutes continue with the upgrade.
There can be scenario where the already checked volume becomes degraded later, so add a …
=> chore(upgrade): fix rebuild validation

chart/templates/mayastor/io/io-engine-daemonset.yaml, chart/values.yaml
Configure crdt via the helm chart, allowing tests to use crdt of 0. 
This is a command retry delay which allows our target to reconfigure the target whilst there is no host IO.
=> Cherry-pick #326

chart/templates/mayastor/io/io-engine-daemonset.yaml, chart/values.yaml
Configure crdt via the helm chart, allowing tests to use crdt of 0. 
This is a command retry delay which allows our target to reconfigure the target whilst there is no host IO.
=> feat(nvmf/crdt): add crdt to the io-engine

k8s/upgrade/src/bin/upgrade-job/common/constants.rs, k8s/upgrade/src/bin/upgrade-job/events/event_recorder.rs, k8s/upgrade/src/bin/upgrade-job/helm/chart.rs, k8s/upgrade/src/bin/upgrade-job/helm/client.rs, k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs, k8s/upgrade/src/bin/upgrade-job/helm/values.rs, k8s/upgrade/src/bin/upgrade-job/helm/yaml/yq.rs, k8s/upgrade/src/bin/upgrade-job/opts/validators.rs
This PR enforces the use of defaults for the following helm chart values, when upgrading to 2.4.0:
- eventing.enabled (only for 2.3.x releases)
- csi.image.provisionerTag
- csi.image.attacherTag
- csi.image.snapshotterTag
- csi.image.snapshotControllerTag
- csi.image.registrarTag
=> feat(upgrade-job): enforce defaults for eventing and csi sidecars

k8s/upgrade/src/bin/upgrade-job/common/error.rs, k8s/upgrade/src/bin/upgrade-job/helm/client.rs, k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs, k8s/upgrade/src/bin/upgrade-job/upgrade.rs
This PR removes the duplicate implementation of the helm upgrade command to allow for a dry-run upgrade command flag inclusion.
The upgrade-job runs the 'helm upgrade --dry-run' command. The implementation for the helm commands api is largely constrained to the helm::client module. However, the dry-run upgrade command is implemented separately in the helm::upgrade module. The dry-run upgrade command is largely similar to the regular upgrade command, and can use the helm::client api. The requirement does not require a separate implementation of the command execution tools in the helm::upgrade module. 
This PR changes the implementation of helm upgrade dry-run to use the existing api. It also defers the execution of the helm upgrade command to another section of the code, by passing a …
=> refactor(upgrade-job): change dry-run helm upgrade implementation 

call-home/src/bin/callhome/main.rs, call-home/src/common/constants.rs, chart/templates/mayastor/obs/obs-callhome-deployment.yaml
This code enables the obs-callhome-stats container when eventing is enabled.
Before, the ops-stats-callhome container was enabled when the call home feature was activated. However, it's unnecessary for the container to run when eventing is disabled. To address this, I've introduced the appropriate condition to activate the stats container when eventing is enabled.
Tested manually
=> fix(eventing): enable stats container when eventing is enabled

k8s/upgrade/src/bin/upgrade-job/helm/values.rs, k8s/upgrade/src/bin/upgrade-job/helm/yaml/yq.rs
This PR fixes a the case when yq sets a value other than a string on to a yaml file (i.e. a bool or a null). This removes the `"` character surrounding the set value when the value set is 'true', 'false', an int or 'null'.
=> fix(upgrade-job): avoid quotes when setting yaml bools, null, int

k8s/upgrade/src/bin/upgrade-job/helm/chart.rs
The upgrade-job parses few specific values from the source mayastor helm chart's values.yaml. These are used to make conditional value 'sets'. Usually these values would always be available in the target helm chart, but it may be absent in the source helm chart (as it may have been added during later releases). It has to assume sane defaults for these values, so that the parse operation does not fail for the source helm chart.
This PR sets default values for 'csi.image.snapshotterTag', 'csi.image.snapshotControllerTag' and 'eventing.enabled'.
**N.B.:**
These default values are not used in the final values set used with the helm upgrade. They are simply used to conveniently make decisions about 'special' yq set operations (e.g. changed default values, etc.). Values yaml for upgrade is …
=> fix(upgrade-job): set defaults for absent helm values

chart/README.md, chart/templates/mayastor/csi/csi-controller-deployment.yaml, chart/values.yaml
`--prevent-volume-mode-conversion`: Boolean that prevents an unauthorised user from modifying the volume mode when creating a PVC from an existing VolumeSnapshot. Only present as an alpha feature in v6.0.0 and above.
We enable the above flag on the csi-provisioner and the csi-snapshot-controller as a default behaviour.
This change is needed so that the users cannot accidently change the volume mode, as changing mode from Block to Filesystem is destructive.
No
This was tested manually. We would also add a bdd scenario to cover this in the e2e system tests.
=> feat(snapshot, restore): prevent volume mode conversion for restore as default behaviour

tests/README.md, tests/minikube/setup.sh, tests/shell.nix
This PR adds testing tools which will be of use when running in-repo tests.
This change adds a new directory and 3 new files.
```console
tests/
├── minikube/
│   └── setup.sh
├── README.md
└── shell.nix
```
The shell script creates a single-node minikube kubernetes cluster. Optionally, it can also pull in (from GitHub) and set up the following dependencies as well:
- https://github.com/Mirantis/cri-dockerd: This is skipped if it already exists. Pulls in released binary and configures systemd service.
- https://github.com/containernetworking/plugins: This is always installed whenever the `--install-prerequisites` option is used.
This script uses kubernetes v1.25.10 by default.
Installs kubectl cli utility of the same version as the configured kubernetes version. Replaces existing kubectl, …
=> feat(tests): add script for creating minikube cluster

chart/README.md, chart/templates/mayastor/io/io-engine-daemonset.yaml, chart/values.yaml
Currently we use `/var/local/io-engine` and `/var/local/local-pv-hostpath/{{ .Release.Name }}`
This is a bit too spread we should bundle it all within a common `/var/local/{{ .Release.Name }}` example:-
`/var/local/{{ .Release.Name }}/{io-engine, localpv-hostpath}`
This PR changes the helm chart to include this.
No
=> fix: /var/local paths should be under release name

chart/values.yaml
With multiline support we define starting point of the log block when it gets filtered through `logcli` parameter. 
Every log that we stdout starts with timestamp(with ansi color char now by default) . In Regex1 , `\x1b\[2m` matches colour unicode pattern. logger adds 2 zero width space also hence Regex has space to match.
We might have uncolored timestamp in future. So In Regex2, we handle that scenario.
Regex1: '^  \x1b\[2m(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}).(\d{6})Z'
Regex2 : '^  (\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}).(\d{6})Z'
=> feat(loki): adding multiline support

.github/workflows/main-chart.yml, k8s/upgrade/src/bin/upgrade-job/common/constants.rs, k8s/upgrade/src/bin/upgrade-job/helm/chart.rs, k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs, k8s/upgrade/src/bin/upgrade-job/helm/values.rs, scripts/helm/publish-chart-yaml.sh, scripts/helm/test-publish-chart-yaml.sh
Upgrade e2e tests are run as a part of release/x.y branches, but not develop or main. This change modifies the chart that is posted to the 'main' branch, and this chart should qualify as a valid target helm chart for upgrade, thus allowing testing code from develop (main branch uses code from develop at a set frequency).
The intention is to be able to upgrade from a released version to develop or main.
Changes to upgrade code:
- Adds support for parsing repotags in the upgrade-job::helm::chart module
- Adds default set options for setting repotags along with image tags. This is required because the main branch chart uses `image.repoTags` instead of `image.tag`.
Changes to publish_chart_yaml.sh script:
- Changes appVersion and version set when generating main branch chart (using the …
=> Changes for testing 'upgrade' from develop branch

scripts/helm/publish-chart-yaml.sh
Whenever the `--check-chart main` option is used with the script scripts/helm/publish_chart_yaml.sh, it lists the URLs for all of the remote refs available. The name of the first remote ref URL matching the URL to this repo (openebs/mayastor-extensions) is picked up. This uses a regex which expects 'openebs/mayastor-extensions' at the end of the URL. However, some folks may use a '.git' at the end of their remote ref URLs. The regex doesn't account for this possibility.
Covers the case for an optional .git at the end of the remote ref for openebs/mayastor-extensions repo.
Helm-core uses a .git. Helm-core is the main consumer for this script's 'main' branch chart features.
No
=> fix(publish_chart): support git remote URLs with '.git' at the end of it

k8s/upgrade/src/bin/upgrade-job/opts.rs
Two clap args introduced in https://github.com/openebs/mayastor-extensions/pull/330 make use the short form option argument. These two arguments -- 'helm_args_set' and 'helm_args_set_file' begin with 'h'. Both of these two args, as well the '--help' option try to make use of '-h'. This change removes the short form arg for these two args.
Remove short args for 'helm_args_set' and 'helm_args_set_file' CliArgs.
`upgrade-job -h` fails.
Yes.
Fixes a regression introduced in  https://github.com/openebs/mayastor-extensions/pull/330
Trivial change, tested the successful execution of `upgrade-job -h`.
=> fix(upgrade-job): remove short args to resolve conflict over '-h' option

nix/pkgs/images/default.nix
For all branches, except for the main branch if '--app-tag <tag>' is set the script fails if the existing version and appVersion of the helm chart on the branch contains a tag with a prerelase extensions. This check makes sense, however, the main branch will always have a prerelase tag. This change relaxes the check for specific chart versions which match the unmistakable main branch version tags.
Changes:
- Ignore prerel check if existing chart version matches the regex for the main branch chart.
- Ignore prerel check if existing chart appVersion matches the regex for the main branch chart.
- Allow for all kinds of diff amongst the APP_TAG, CHART_VERSION, CHART_APP_VERSION for not only `--check-chart main`, but also `--app-tag <main-branch-style-tag>`
Helm core
No.
Tested using the test …
=> feat(publish_chart): relax prerel absent check for existing chart

chart/README.md, chart/values.yaml
This bumps the csi sidecars for external-snapshotter and node-driver-registrar to minimum versions which support csi spec v1.8.0. The other sidecars are at par.
=> chore(chart): bump snapshot and registrar csi sidecar versions

call-home/src/bin/stats/cache/events_cache.rs
When upgrading Mayastor 2.4 to develop the stats events-cache fails to initialise from events-store config map because the events-store does not have the nexus event-data and the stats container fails.
Added #[serde(default)] to the events-cache to initialise the events-cache with default values if the events-store misses any keys(nexus). 
Manually tested.
=> feat(eventing): update events-cache missing fields from events-store with default values

.github/workflows/release-binaries.yml
Ensure released binaries are executable.
Removes the need to `chmod +x` after downloading. Also, allows this to be added to the `krew-index` for easy installation.
No.
Ran CI on my fork. There doesn't seem to be a step which uploads the artifacts to the GitHub release though.
=> ci: ensure released binaries are executable 

.github/workflows/release-binaries.yml, Cargo.lock, default.nix, nix/lib/rust.nix, nix/overlay.nix, nix/pkgs/extensions/cargo-project.nix, nix/pkgs/utils/default.nix, shell.nix
Cross compile aarch64-linux static binary from x86_64-linux.
Refactor the static binary building to allow cross-compilation.
Also simplifies adding a new binary by adding generic builders.
Building aarch64 binaries.
=> Build aarch64-linux binaries for the kubectl-plugin

chart/templates/storageclass.yaml, chart/values.yaml
This pull request aims to allow the customization of the `storageClass` created by the mayastor helm chart.
The following capabilities are added for the `storageClass`:
- Allow to disable the creation
- Allow to set the `storageClass` as the default one
- Allow to set the replication factor
- Allow to set the name
The main motivation for those changes is to make the `storageClass` configurable and usable as default in a k8s cluster without the need to create a second one from a separate set of manifests.
No
Tested by deploying Mayastor into a kubernetes cluster and validating that the template is rendered as valid k8s yaml.
=> feat(chart): allow to customize the storageclass

.gitmodules
Used for importing the control-plane to this repo. Also update commit of dependency.
Use a relative URL for importing the control-plane submodule.
The top-level part of the URL is the same between repos, so need not be duplicated,
and can be inferred from the URL of the parent repo.
No
Tested by building locally and via CI.
=> fix: use relative url for submodule

.github/workflows/main-chart.yml, scripts/helm/publish-chart-yaml.sh, scripts/helm/test-publish-chart-yaml.sh
Modify github action and publish-chart-yaml.sh to support helm-testing/* branches
- Modify github action  to support helm-testing/* branches created for release branches
- Modify publish-chart-yaml.sh to support helm-testing/* branches 
This change will publish helm chart to system test helm registry for release branches
No
Tested locally
=> Modify github action and publish-chart-yaml.sh to support helm-testing/<release> branches

.github/workflows/main-chart.yml
- exclude staging and staging-merge branches from publishing charts to helm registry
=> fix: exclude staging and staging-merge branches from chart publish

k8s/upgrade/src/bin/upgrade-job/common/constants.rs, k8s/upgrade/src/bin/upgrade-job/common/error.rs, k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs, k8s/upgrade/src/bin/upgrade-job/upgrade/data_plane.rs, k8s/upgrade/src/bin/upgrade-job/upgrade/utils.rs
Requires #377.
Changes:
- Disables node drain during data-plane upgrade if, for a node a frontend_node of a volume target lies on a node which is ANA-incapable.
=> feat(upgrade-job): disable drain when frontend node is ANA-incapable

chart/values.yaml, k8s/upgrade/src/bin/upgrade-job/common/constants.rs, k8s/upgrade/src/bin/upgrade-job/helm/chart.rs, k8s/upgrade/src/bin/upgrade-job/helm/values.rs
In 2.5.0, the scrapeConfigs options is changed (ref: #344). This adds values changes for upgrade when going from a source version <2.5.0 to a target version >=2.5.0.
Changes:
- Sets .promtail.config.snippets.scrapeConfigs for upgrade from anywhere in the range 2.0.0-rc.1 - 2.4.0.
- Changes loki scrapeConfig to use single quotes, because [the code here](https://github.com/openebs/mayastor-extensions/blob/develop/k8s/upgrade/src/bin/upgrade-job/helm/yaml/yq.rs#L178) adds double quotes to strings, avoiding bools, null and ints. When double quotes are added to scrapeConfigs, it'll require the double quotes withing the scrapeConfigs to use escapes (\\").
=> feat(upgrade): add special values options for 2.5.0 

chart/README.md, chart/templates/mayastor/csi/csi-node-daemonset.yaml, chart/templates/mayastor/io/io-engine-daemonset.yaml, chart/templates/storageclass.yaml, chart/values.yaml
Add more nvme knobs.
Allow controlling nvme timeouts and q depth.
In some virtual environments (non-nvme), the backend can be slower and lead into timeouts and degraded replicas.
More back-pressure work is required to ensure we don't attempt rebuilds and further IO on a backend which is "stuck", but this will give us some hooks for testing etc.
=> feat(helm/nvme): add more knobs to control timeouts and qdepth

chart/Chart.yaml, chart/README.md, chart/values.yaml
Cherry-pick PR386
Fixes issue where promtail is never ready when no related Mayastor pod is running on a given node.
Cherry-pick issue raised by user.
=> Cherry-pick #386

chart/templates/_helpers.tpl, chart/templates/storageclass.yaml, chart/values.yaml, k8s/upgrade/src/bin/upgrade-job/helm/yaml/yq.rs, k8s/upgrade/src/plugin/preflight_validations.rs
Change:
- Use yq's strenv operator to use special characters with yq when updating the upgrade values.yaml.
- Fix check which forbids upgrade from a stable release to unstable version.
- Prefers the parameters of an existing default StorageClass over the chart defaults.
=> fix: fix upgrade

scripts/utils/advisory_lock.sh, scripts/utils/log.sh
The utils scripts are meant to be imported by other scripts. Setting/unsetting
set options on these scripts may interfere with the set options on the calling
script. The set options aren't an essential part of the scripts, removing them.
=> chore(scripts/utils): remove set options

chart/Chart.yaml, chart/README.md, chart/values.yaml
Fixes https://github.com/openebs/mayastor/issues/1560.
No.
Running with current helm chart and this configuration:
```yaml
loki-stack:
promtail:
config:
file: |
server:
log_level: {{ .Values.config.logLevel }}
http_listen_port: {{ .Values.config.serverPort }}
{{- tpl .Values.config.snippets.extraServerConfigs . | nindent 2 }}
clients:
- url: {{ tpl .Values.config.lokiAddress . }}
{{- with .Values.config.snippets.extraClientConfigs }}
{{- toYaml . | nindent 2 }}
{{- end }}
positions:
filename: /run/promtail/positions.yaml
scrape_configs:
{{- tpl .Values.config.snippets.scrapeConfigs . | nindent 2 }}
{{- tpl .Values.config.snippets.extraScrapeConfigs . | nindent 2 }}
snippets:
extraServerConfigs: |-
health_check_target: false
```
The `{{- tpl .Values.config.snippets.extraServerConfigs . | …
=> Update `loki-stack` and set `health_check_targets: false`.

k8s/upgrade/src/bin/upgrade-job/upgrade/utils.rs
Fixes a bug where if, during data-plane upgrade, `rebuild_result` function finds unhealthy volumes, but none of the volumes have a target, then, the function continues to try to list unhealthy volumes constantly.
Adds a break from the infinite loop for an empty target accumulator.
Adds a break from the infinite loop for an empty target hashset.
=> fix(upgrade-job): avoid infinite loop when no unhealthy vols have a target

chart/README.md, chart/values.yaml
The `lokiAddress` key is no longer useful with the new loki-stack helm chart. Clients are now input into the `clients[]` array.
Ref: https://github.com/grafana/helm-charts/pull/1425
=> fix(chart): promtail subchart changes for chart v6.13.1

k8s/upgrade/src/bin/upgrade-job/common/constants.rs, k8s/upgrade/src/bin/upgrade-job/common/error.rs, k8s/upgrade/src/bin/upgrade-job/helm/chart.rs, k8s/upgrade/src/bin/upgrade-job/helm/upgrade.rs, k8s/upgrade/src/bin/upgrade-job/helm/values.rs, k8s/upgrade/src/bin/upgrade-job/helm/yaml/yq.rs, nix/pkgs/images/default.nix, scripts/helm/generate-consolidated-values.sh, scripts/release.sh
Requires #386.
Overview:
- adds new yq commands to delete objects, append to objects, and append to arrays.
- adds special upgrade values.yaml update for loki-stack changes from #386. Introduces migrations and set_literal_value updates to alter the existing yaml till it resembles the new one.
- replaces all `&Path` is the `helm::yaml::yq` module with `AsRef<Path>`.
Changes:
- removes .loki-stack.loki.config.ingester.lifecycler.ring.kvstore as it
does not exist in loki-stack v2.9.11
- adds set value for the grafana/loki container image tag
- removes .loki-stack.promtail.config.snippets.extraClientConfigs as it
does not exist in loki-stack v2.9.11
- removes .loki-stack.promtail.initContainer as it does not exist in loki-stack
v2.9.11
- migrates .loki-stack.promtail.config.lokiAddress to …
=> feat(upgrade-job): add support for loki-stack helm chart upgrade

k8s/upgrade/src/bin/upgrade-job/helm/chart.rs, k8s/upgrade/src/bin/upgrade-job/helm/values.rs
Changes:
1. The localpv-provisioner helm chart was updated to v3.5.0 with the release of Mayastor v2.5.0. The yq merge would retain the release-version and image tags on the localpv helm values. They need to be manually overriden.
2. The scrapeConfigs change is only applied if the source configuration is the older default. It should move to newer default, only if the chart had the older default to begin with. This prevents overriding user-defined custom configuration.
=> fix: upgrade-job fixes

.github/workflows/pr-commitlint.yml, commitlint.config.js
This should address the inifite rebuild issue when no code change is made. Dev UX should now improve as consecutive cargo builds should not rebuild.
=> build: update control-plane submodule addressing infinite rebuilds

Cargo.lock, k8s/plugin/Cargo.toml, k8s/plugin/src/main.rs, k8s/plugin/src/resources/mod.rs, k8s/supportability/Cargo.toml, k8s/supportability/src/lib.rs, k8s/upgrade/src/plugin/upgrade.rs
Separate command execution from error handling.
Make use of common cli args and execution trait to remove redundant code. Remove excessing error mapping code.
todo: make execution trait even more generic (in the rest-plugin crate side) Currently the cli args for supportability rely on the fact that clap global allows us to specify "duplicates". I'm not sure if this is a good idea.. todo: Build dump cli args explicitly?
=> refactor(kubectl-plugin): tidy up error handling and command execution
